version: '3.8'

services:
  bot:
    build: .
    environment:
      - APP_DATABASE_URL=postgres://user:password@host:5432/dbname?sslmode=require
      - APP_TELEGRAM_TOKEN=your_token
      - APP_OWNER_ID=your_telegram_id
