version: '3.8'

services:
  bot:
    build: .
    environment:
      - APP_DATABASE_HOST=db
      - APP_DATABASE_PORT=5432
      - APP_DATABASE_USER=postgres
      - APP_DATABASE_PASSWORD=secret
      - APP_DATABASE_NAME=telegram_bot
      - APP_DATABASE_SSLMODE=disable
      - APP_TELEGRAM_TOKEN=your_token
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=telegram_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 